### ISSUE TITLE
CODE d8016

### ISSUE THREAD

**Issue by hKlima** [brat-volk/MagikIndex#1]
![image](https://user-images.githubusercontent.com/112415621/187246168-4512676f-160e-4b8f-9776-fae372da736f.png)

I'm having this problem when compiling

**Comment by brat-volk** [comment]
Disable Run-Time Checks in Project Properties.
So just set "Project Properties -> C/C++ -> Code Generation -> Basic RunTime Checks" to "Default".
Please do comment again under this reply to let me know if the problem is fixed.

**Comment by hKlima** [comment]
yes, but now it show this: C1083
![image](https://user-images.githubusercontent.com/112415621/187293846-b6cb20a2-bed7-4fe6-a99c-20902616e07e.png)

**Comment by hKlima** [comment]
sorry, these:
![image](https://user-images.githubusercontent.com/112415621/187294967-7e9f41d1-ed54-48c2-8c99-21fda0bd78b1.png)

**Comment by brat-volk** [comment]
Comment out ' #include "lz4/lz4.h" ' from common.h. ( this can be done by adding // before the aforementioned code )
Then delete the entire CompressFile() function from Log.cpp. (it should be about line 219 to 235, doublecheck to be sure)
This should fix the errors regarding "lz4.h".
To fix the one about "base64.h" just replace ' include ".../MagikIndex/base64.h" ' with ' #include "base64.h" ' and make sure that base64.h is indeed in the same directory as MagiKrypt.cpp.

Like before, post a comment to update me on the issue.

**Comment by hKlima** [comment]
The problems regarding the lz4 was fixed, but I didn't understand what I am suppose to do with the base64

I did this:
![image](https://user-images.githubusercontent.com/112415621/187303865-65a852bf-a5ed-41aa-9c5b-5e5a5cc47f76.png)
and now I have to do what?

**Comment by brat-volk** [comment]
Remove ' #include "base64.h" ' at line 6.

**Comment by hKlima** [comment]
there is still this one:
![image](https://user-images.githubusercontent.com/112415621/187305620-176a482a-ded7-4db4-a40e-02e75b877725.png)

**Comment by brat-volk** [comment]
Are you sure that you removed the correct line?
Also can you post a screenshot of your directory structure?
because depending on where you put "base64.h" you will have to place the correct path to it in the includes

**Comment by hKlima** [comment]
![image](https://user-images.githubusercontent.com/112415621/187306792-a2c0f185-f9c2-42be-bac7-83d2184bff9c.png)

**Comment by hKlima** [comment]
I'm kinda new to this stuff, so I don't know if I'm doing it right

**Comment by brat-volk** [comment]
Lets just move this to Discord so we can comunicate better.
Add  berlusconibestwaifu#2075  .

**Comment by brat-volk** [comment]
> I'm kinda new to this stuff, so I don't know if I'm doing it right

Don't worry! 
Everyone has to start somewhere ^^

**Comment by brat-volk** [comment]
The user had a Release/Debug .lib dependency mismatch, it's now been fixed. :)
