### ISSUE TITLE
Compile error C2601. 

### ISSUE THREAD

**Issue by meanjellybean1** [brat-volk/MagikIndex#2]
Trying to complete the build after following your instructions but am getting hit with the following errors:
![image](https://user-images.githubusercontent.com/56918112/189644070-46d38541-6ffe-4937-8321-2e449de41bce.png)

**Comment by brat-volk** [comment]
After a quick Google search it looks like an issue with a missing "}" at the end of WinMain().

**Comment by brat-volk** [comment]
I might be wrong though, so please, text me on Discord( berlusconibestwaifu#2075 ) so i can help you out.
